### ISSUE TITLE
Dynamic OG Image Generation Not Working - Server Setup Required

### ISSUE THREAD

**Issue by savvar9991** [aptos-labs/developer-docs#735]
### Url

https://github.com/aptos-labs/developer-docs/blob/f10a019751ff32603414932c23a50d4ad2eb5b63/apps/nextra/pages/en/developer-platforms/contribute/setup/SEO.mdx

## Issue Description
The dynamic OG image generation example in the documentation requires a properly configured development server, but currently it's not working due to missing setup.

## Current Behavior
- Dynamic image generation fails
- Accessing `http://localhost:3000/api/og.png` returns connection refused
- Component `DynamicImage` cannot load images
![image](https://github.com/user-attachments/assets/478ddee8-0cbf-4e3a-8133-c7a87d52c374)

### Section

sdks

**Comment by hariria** [comment]
I believe you might be using the wrong port number, should be 3030.

It seems to be working for me in two places

1. https://aptos.dev/api/og.png

2. Shows up in the OG image embedded in the docs: https://aptos.dev/en/developer-platforms/contribute/setup/SEO


LMK if this is different from what you're referring to

**Comment by savvar9991** [comment]
Thank you for your assistance. I tried using port 3030 as you suggested, and also checked port 3000, but unfortunately, the issue persists. Locally, I am still unable to access the dynamically generated Open Graph images, while everything works correctly on the production server.
Additionally, I would like to note that I did not originally implement this feature, and according to the version history, it appears that it has never functioned correctly locally. This might suggest that there could be an underlying issue that has been overlooked.
Could you share the details of your server configuration or provide information on what settings or dependencies might be crucial for this functionality to work correctly? There might be specific server setup steps that I missed.

**Comment by hariria** [comment]
Hmmm, it works fine for me and has worked for me since I implemented the feature... Did you do `pnpm build` and `pnpm start`? The opengraph is dynamic so it won't load anything in the Github markdown preview. See below. Maybe try that? For now I will close this issue since it seems to be working properly locally and in production

http://localhost:3030/api/og.png: <img width="1101" alt="Screenshot 2024-12-11 at 5 05 29 PM" src="https://github.com/user-attachments/assets/8fdc9d48-ad8f-43d0-8c11-f09c02599528" />

It's also loading properly on the contribute page.
<img width="1095" alt="Screenshot 2024-12-11 at 5 07 21 PM" src="https://github.com/user-attachments/assets/98d672e7-e253-4eaf-a033-32eff2fa0098" />
