### ISSUE TITLE
[Bug] Testnet Faucet API (faucet.testnet.aptoslabs.com) returns 500 Internal Server Error

### ISSUE THREAD

**Issue by kakedashi3** [aptos-labs/developer-docs#741]
https://aptos.dev/en/network/faucet

I was able to mint tokens through Google authentication from the above URL. Thank you.

**Comment by igor-p** [comment]
There was a button to log in via GitHub, but the authentication wasn't working with the faucet, so we are temporarily disabling logging in with GitHub for now.

Also, it seems like errors regarding JWT tokens are responding with `500` instead of `4xx`. There's an issue for that in https://github.com/aptos-labs/aptos-core/issues/15560

**Comment by igor-p** [comment]
Closing this as we have disabled GitHub login, and logging in with Google is working fine as an alternative for now.
